### ISSUE TITLE
clang-16 support?

### ISSUE THREAD

**Issue by antonysigma** [fix8mt/f8fiber#12]
Other than Linux OS requirement, what is the requirement of the compiler and toolchain?

When I try to build the examples with `clang-16` on Ubuntu Linux, the compiler complains about this error:

```
fiber/include/fix8/fiber.hpp:331:24: error: constexpr function's return type 'f8_stack_ptr' (aka 'unique_ptr<f8_stack>') is not a literal type
```

**Comment by dakka** [comment]
Yes, clang 16 was upset about non-constexpr `~std::unique_ptr()`. I have pushed a fix to main.

**Comment by antonysigma** [comment]
Thank you for the quick response. The fix works for the non-constexpr unique_ptr. But then the compiler choked on other errors. Examples are:

```
fiber/include/fix8/fiber.hpp:105:29: error: no member named 'wait' in 'std::atomic_flag'
        void lock() noexcept { _sl.wait(true); } // std::memory_order_seq_cst
```

Do you recommend gcc compiler? If so, what is the minimum version of `gcc` to compile this project?

Or, I can also contribute a Github CI job to validate clang or gcc builds.

**Comment by dakka** [comment]
I built it it clang 16, 18 in my testing without those errors. Might be environmental.
`clang --version
Ubuntu clang version 16.0.6 (23ubuntu4)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin`

> Or, I can also contribute a Github CI job to validate clang or gcc builds.

All help appreciated!

**Comment by antonysigma** [comment]
Thanks. Likely the `-stdlib=libc++` or `-stdlib=libstdc++` in my environment contains outdated stdlib. Closing this thread.
